### ISSUE TITLE
"Sign up to Mito" Splash screen appearing after updating Mito

### ISSUE THREAD

**Issue by twelsh37** [mito-ds/mito#137] opened 2022-03-07 20:09 UTC
**Describe the bug**
Having upgraded to the latest version of mito I am receiving the "sign up to mito" splash screen

**To Reproduce**
Steps to reproduce the behaviour:
ackage             Version Latest  Type
------------------- ------- ------- -----
mitoinstaller       0.0.117 0.0.119 sdist
mitosheet           0.1.388 0.1.390 wheel
1.From Mitoinstaller v 0.0.117 and mitosheet v 0.1.388 upgrade
```
python -m pip install mitoinstaller
python -m mitoinstaller install
```
2. On running mitosheet after the install I get the splash screen

**Expected behavior**
I would expect mito installer to note previous versions and not pop up the splash screen

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Mito Version mito 0.1.388 -> 0.1.390

**Comment by naterush** [comment] 2022-03-07 21:25
@twelsh37 thanks for the bug report! This is certainly not intended behavior - and we want to get this fixed ASAP. 

To help us narrow down the issue, can you try running these same commands again and let me know if it asks you to upgrade again?

I'll get this fixed up ASAP once we get this narrowed down. Thanks again!

**Comment by naterush** [comment] 2022-03-07 21:29
If it does ask you to upgrade once again, then what must be happening is that your user.json file is getting overwritten with each upgrade. I'm not sure how this would be happening, given the current logic (which explicitly appears to not overwrite the user.json file in either an install or upgrade)...

**Comment by twelsh37** [comment] 2022-03-07 22:16
Hey @naterush, This is the first time in a long time I have seen this happen. I try and keep up to date with the releases. 
I just did the installation again in my environment but this time I did not get the new user dialogue. I will keep an eye out if it happens on the next upgrade.

What is the location of the user.json file? I will check the timestamp and modification date

**Comment by naterush** [comment] 2022-03-14 21:30
Note - I just got this bug as well! Super weird. It's some non-deterministic error that is occurring... because when I promptly ran the command again, it didn't occur. I do not know why this would be.

**Comment by twelsh37** [comment] 2022-03-15 22:08
Just upgraded to the latest version and I did not get the error when I missed off --install

From !pip list
```txt
mitoinstaller       0.0.123
mitosheet           0.1.393
```

install was as follows

```py
python -m pip install mitoinstaller
python -m mitoinstaller install
```

**Comment by naterush** [comment] 2022-03-21 22:45
Good to know! We deployed a fix that should make this bug less likely (although I'm confused how it is even happening in the first place). 

I'm gonna rename this issue and keep it around, so we have a place to collect data on it. Please do let me know if you run into this again!

**Comment by naterush** [comment] 2023-11-06 18:17
Closing as we're removing this signup flow in the future!

**Closed by naterush** 2023-11-06 18:17 UTC
Labels: priority: high, waiting on: information
