### ISSUE TITLE
Problem file reads in st.dataframe but not Mio

### ISSUE THREAD

**Issue by fredzannarbor** [mito-ds/mito#1307] opened 2024-06-16 22:34 UTC
**Describe the bug**
A spreadsheet that I can read properly in st.dataframe but not mito.

Loads properly, but any sort or column activity such as get values/stats causes the app to drop back to the first column of the home dataframe.

**To Reproduce**
Load file and try to sort or get stats on any column.
@naterush has the file which has proprietary info.

**Expected behavior**
Complete the sort.

**Desktop (please complete the following information):**
Mac OS/Chrome

**Additional context**

This is mission-critical for me.

**Comment by naterush** [comment] 2024-06-26 17:49
@fredzannarbor per your email, closing this as addressed. If you ever dig up the root cause, feel free to open again.

**Closed by naterush** 2024-06-26 17:49 UTC
